build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
images:
- context_dir: base/ubi9-python-3.9
  dockerfile_path: Dockerfile
  to: base-ubi8-python-3.9
- context_dir: test/ubi9-python-3.9
  dockerfile_path: Dockerfile
  from: base-ubi9-python-3.9
  to: test-ubi8-python-3.9
promotion:
  namespace: atheo89
  tag: latest
releases:
  latest:
    release:
      architecture: amd64
      channel: fast
      version: "4.10"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
zz_generated_metadata:
  branch: main
  org: atheo89
  repo: secrets-test
