build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-8-release-golang-1.17-openshift-4.10
images:
- context_dir: base/ubi8-python-3.8
  dockerfile_path: Dockerfile
  to: base-ubi8-python-3.8
  secrets:
  - mount_path: "/secret"
    name: "test-odh-nb-credentials"
  context_dir: jupyter/minimal/ubi8-python-3.8
  dockerfile_path: Dockerfile
  from: base-ubi8-python-3.8
  to: jupyter-minimal-ubi8-python-3.8

promotion:
  namespace: opendatahub-io
  tag: latest
releases:
  latest:
    release:
      architecture: amd64
      channel: fast
      version: "4.10"
resources:
  '*':
    requests:
      cpu: 200m
      memory: 400Mi
    workflow: ipi-gcp
zz_generated_metadata:
  branch: main
  org: atheo89
  repo: notebooks
